server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: service-user
          uri: lb://SERVICE-USER
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
            - RequestTime=true
        - id: service-product
          uri: lb://SERVICE-PRODUCT
          predicates:
            - Path=/product/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug